services:
  redis:
    image: redis:7.4.1
    container_name: ${REDIS_HOST:-redis}
    env_file:
      - .env
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 3s
      timeout: 5s